# Generated by Django 6.1 on 2026-08-14 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='VAT %% applied to the subtotal. Set to 0 for a tax-exempt quote.', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Scope notes shown on the quote, above the line items.')),
                ('terms', models.TextField(blank=True, default='50% deposit on acceptance, balance on completion. Quote valid for 30 days from issue date unless stated otherwise. Materials sourced to spec unless an alternative is agreed in writing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(blank=True, help_text='Optional — the lead this quote was raised from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.quoterequest')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(default='unit', help_text='e.g. unit, hrs, m, lot', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.quote')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
