# Generated by Django 5.2.17 on 2026-08-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_id_alter_quote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown on the service card and detail page. Falls back to a branded category cover graphic when left blank.', null=True, upload_to='services/'),
        ),
    ]
