# Generated by Django 5.0.7 on 2026-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section image displayed on the home page.', null=True, upload_to='hero/')),
                ('services_video', models.FileField(blank=True, help_text='Video shown in the services section.', null=True, upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Video file for this project.', null=True, upload_to='project_videos/'),
        ),
    ]
