# Generated by Django 5.0.7 on 2026-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(default='kagunyesam@gmail.com', help_text='Contact email address displayed on the site', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password or app-specific password', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP username (usually email address)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP server port (e.g., 587 for TLS)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for email sending'),
        ),
    ]
