# Generated by Django 5.0.7 on 2026-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='technician_email',
            field=models.EmailField(default='warrenm@voltpro.co.ke', help_text='Technician email address for receiving quote notifications', max_length=254),
        ),
    ]
