# Generated by Django 4.2.30 on 2026-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_technician_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(default='info@voltproelectrodata.co.ke', help_text='Contact email address displayed on the site', max_length=254),
        ),
    ]
