# Generated by Django 4.2.30 on 2026-08-20 08:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_siteconfiguration_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name for dropdown', max_length=200)),
                ('description', models.CharField(help_text='Default description', max_length=200)),
                ('unit', models.CharField(default='unit', help_text='e.g. unit, hrs, m, lot', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('category', models.CharField(blank=True, help_text='Category for grouping', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show in dropdown')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order in dropdown')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Select from inventory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='core.inventoryitem'),
        ),
    ]
