# Generated by Django 4.2.30 on 2026-08-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inventoryitem_quotelineitem_inventory_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotelineitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='quotelineitem',
            name='order',
        ),
    ]
