# Generated by Django 4.2.30 on 2026-08-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_quotelineitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelineitem',
            name='inventory_item',
        ),
    ]
