# Generated by Django 4.2.30 on 2026-08-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_quotelineitem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Select from inventory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='core.inventoryitem'),
        ),
    ]
