# Generated by Django 4.2.30 on 2026-08-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quotelineitem_inventory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelineitem',
            name='inventory_item',
        ),
    ]
