# Generated by Django 4.2.30 on 2026-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_quotelineitem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='apply_vat',
            field=models.BooleanField(default=True, help_text='Check to apply VAT to this quote'),
        ),
    ]
