# Generated by Django 4.2.30 on 2026-08-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quote_apply_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='apply_vat',
        ),
    ]
