# Generated by Django 4.2.30 on 2026-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_quote_apply_vat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotelineitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
