# Generated by Django 4.2.30 on 2026-08-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_quotelineitem_options_quotelineitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotelineitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='quotelineitem',
            name='order',
        ),
    ]
