# Generated by Django 4.2.30 on 2026-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_quotelineitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='technician_email',
            field=models.EmailField(blank=True, help_text='Technician email address', max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='technician_name',
            field=models.CharField(blank=True, help_text='Technician assigned to this quote', max_length=120),
        ),
        migrations.AddField(
            model_name='quote',
            name='technician_phone',
            field=models.CharField(blank=True, help_text='Technician contact number', max_length=30),
        ),
    ]
