# Generated by Django 4.2.30 on 2026-08-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_quote_technician_email_quote_technician_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='technician_email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='technician_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='technician_phone',
        ),
    ]
