# Generated by Django 4.2.30 on 2026-08-21 07:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_quote_technician_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotelineitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Quote Line Item', 'verbose_name_plural': 'Quote Line Items'},
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order for line items'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Client email address for sending quote and updates', max_length=254),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_location',
            field=models.CharField(blank=True, help_text='Physical address or location where work will be performed', max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_name',
            field=models.CharField(help_text='Full name of the client or organization contact person', max_length=120),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Client phone number for communication', max_length=30),
        ),
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, help_text='Scope notes shown on the quote, above the line items. Describe the work scope, inclusions, and exclusions.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='VAT percentage applied to the subtotal. Set to 0 for a tax-exempt quote.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True, default='50% deposit on acceptance, balance on completion. Quote valid for 30 days from issue date unless stated otherwise. Materials sourced to spec unless an alternative is agreed in writing.', help_text='Payment terms, validity period, and other conditions shown on the quote'),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='description',
            field=models.CharField(help_text='Detailed description of the item, material, or service', max_length=200),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit',
            field=models.CharField(default='unit', help_text='Unit of measurement (e.g. unit, hrs, m, lot, kg)', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per unit in KES', max_digits=12),
        ),
    ]
