# Generated by Django 4.2.30 on 2026-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_quotelineitem_options_quotelineitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='taxable',
            field=models.BooleanField(default=True, help_text='Whether this item is subject to VAT'),
        ),
    ]
