# Generated by Django 4.2.30 on 2026-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_quotelineitem_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='apply_tax',
            field=models.BooleanField(default=True, help_text='Whether to apply tax to this quote. If unchecked, no tax will be calculated.'),
        ),
    ]
