# Generated by Django 4.2.30 on 2026-08-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_quote_apply_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='apply_tax',
        ),
    ]
