# Generated by Django 5.0.6 on 2026-08-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_quote_apply_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(default='VoltPro Team', max_length=100)),
                ('excerpt', models.CharField(help_text='Short summary shown in blog listing and meta description', max_length=300)),
                ('content', models.TextField(help_text='Full article content. You can use HTML for formatting.')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog/')),
                ('category', models.CharField(default='General', help_text="Category for grouping posts (e.g., 'Solar', 'Security', 'Tips')", max_length=50)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the post is visible on the site')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured posts show prominently')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description for search engines', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=200)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='quotelineitem',
            name='taxable',
        ),
    ]
