# Generated by Django 4.2.30 on 2026-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_quote_apply_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='taxable',
            field=models.BooleanField(default=True, help_text='Whether this item is subject to 16% VAT'),
        ),
    ]
