# Generated by Django 5.2.17 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='taxable',
            field=models.BooleanField(default=True, help_text='Whether tax (VAT) should be applied to this line item'),
        ),
    ]
