# Generated by Django 5.2.17 on 2026-09-23 13:56

import core.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_quotelineitem_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to=functools.partial(core.models._unique_upload_to, *('blog',), **{})),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.models._unique_upload_to, *('projects',), **{})),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Video file for this project.', null=True, upload_to=functools.partial(core.models._unique_upload_to, *('project_videos',), **{})),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown on the service card and detail page. Falls back to a branded category cover graphic when left blank.', null=True, upload_to=functools.partial(core.models._unique_upload_to, *('services',), **{})),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section image displayed on the home page.', null=True, upload_to=functools.partial(core.models._unique_upload_to, *('hero',), **{})),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='services_video',
            field=models.FileField(blank=True, help_text='Video shown in the services section.', null=True, upload_to=functools.partial(core.models._unique_upload_to, *('videos',), **{})),
        ),
    ]
