# Generated by Django 5.2.17 on 2026-09-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_quote_standard_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='technician_email',
            field=models.EmailField(default='info@voltpro.co.ke', help_text='Technician email address for receiving quote notifications', max_length=254),
        ),
    ]
